# Generated by Django 5.1.6 on 2025-02-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='x',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='y',
            field=models.TextField(blank=True, null=True),
        ),
    ]
